server.port=8081
spring.application.name=custom-print-service

spring.datasource.url=jdbc:mysql://localhost:3306/custom_print_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

custom-print.maintenance.admin-attention-cron=0 0 3 * * *
custom-print.maintenance.customer-reminder-delay=PT6H
custom-print.maintenance.admin-attention-hours=48
custom-print.maintenance.customer-response-hours=72
custom-print.maintenance.auto-archive-days=30
